
- hosts: all
  sudo: yes
  remote_user: jomaenfe

  tasks:
  - name: Añadir repo de python
    apt_repository: repo=ppa:deadsnakes/ppa state=present

  - name: Actualizar sistema
    command: sudo apt-get update

  - name: Instalar Git
    command: sudo apt-get install -y git
  
  - name: Instalar python version 3.6
    apt: pkg=python3.6 state=present
  
  - name: Cambiando la versión de python
    command: sudo ln -sfn /usr/bin/python3.6 /usr/bin/python

  - name: Instalar pip3
    command: sudo apt-get -y install python3-pip

  - name: Clonar GitHub
    git: repo=https://github.com/jomaenfe/Planificador_diario-IV1819.git  dest=planificador-diario/ force=yes

  - name: Instalar requirements
    command: pip3 install -r planificador-diario/requirements.txt